config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :categories do
       resources :tabs do 
           collection do
             post :render_table
             post :render_table_table
           end
           resources :notifications do
             collection do
                post :notify
             end  
           end   
       end
    end#, only: [:new,:create, :edit, :update, :index]
    resources :accounts 
    resources :admin_users do
      collection{
        post :import
        post :export
        post :send_credential
        get :suspend_user
      }
    end
    get 'accounts/index'
    get 'sessions/login'
    post "sessions/create"
    delete "sessions/destroy"
    get "dashboard/home"
    get "sessions/forgot_password"
    post "password_resets/send_reset_password"
    get "/password_resets/reset_password"
    put "/password_resets/update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # post 'auth/login', to: 'users#login'
  # get 'test', to: 'users#test'
  get "/create_session", to: "admin/tabs#create_session"
  resources :exportdata do
      collection do
        get :exportxls
      end 
    end
  
  post 'phone_verifications/voice' => 'api/v1/phone_verifications#voice'

  api_version(:module => "api/V1", :header => {:name => "Accept", :value => "application/Wavedio; version=1"}) do
  	resources :sessions do
	  	collection do
	  		post :login
	  		post :verify_otp
        post :social_login
        post :call_verification
        post :logout
	  	end 
  	end
  	resources :static_contents do
  		collection do
  			post :static_contents
        get :faqs
        get :additional_topic
        post :query
  		end
  	end
    resources :devices do
      collection do
        post :search_device
        post :device_locations
        post :stolen_device_location_update
        post :device_location_search
        post :device_status
        post :save_battery_ts
      end
    end
    resources :packages do
      collection do
        get :packages_list
      end
    end
    resources :users do
      collection do
        post :apply_credit
        post :charge_history
        get :user_last_charge
        post :checksum
        post :billing_not_rated
        post :charging_status
        post :checksum_add_money
        post :add_money_transaction_status
        post :billing_status
      end
    end
    
    resources :help do 
       collection do
         get :get_b1_b2_list
         post :submit_b1_b2
         get :feedback_and_faq_list
         get :r1_r2_list
         post :submit_feedback_api
       end
    end

    resources :transactions do
      collection do
        post :package_payment
        post :send_paytm_otp
        post :validate_paytm_otp
        post :check_paytm_balance
        post :validate_paytm_access_token
        post :paytm_withdraw_api
      end
    end

    resources :payment_methods do 
       collection do 
         get :list
         post :add
         post :remove
       end
    end

  #   resources :phone_verifications do
  #     collection do
  #       post :voice
  #     end
  #   end

end

end

app/models/notification.rb
class Notification
  include Mongoid::Document
  field :admin_user_id, type: String
  field :type, type: String
  field :tab_id, type: String 
  belongs_to :tab
  belongs_to :admin_user 
end

app/controllers/admin/notifications_controller.rb
require 'will_paginate/array'
class Admin::NotificationsController < ApplicationController
  layout 'admin_lte_2'
  before_action :authenticate_admin_user

  def index
    # @admin_user = AdminUser.where(id: session[:user_id]["$oid"]).first
    # category  = Category.find_by(name: "SuperAdmin")
    if params[:search].present?
    @search = AdminUser.any_of({first_name: Regexp.new(".*#{params[:search]}.*","i")},{last_name: Regexp.new(".*#{params[:search]}.*","i")},{emp_id: Regexp.new(".*#{params[:search]}.*","i")},{email: Regexp.new(".*#{params[:search]}.*","i")},{phone: Regexp.new(".*#{params[:search]}.*","i")},{department: Regexp.new(".*#{params[:search]}.*","i")},{designation: Regexp.new(".*#{params[:search]}.*","i")},{territory: Regexp.new(".*#{params[:search]}.*","i")})
    @users = @search.where(:category_id.nin=> Category.where(name: "SuperAdmin").pluck(:id)).order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    # AdminUser.where(:category_id.nin=> Category.where(name: "SuperAdmin").pluck(:id))
    else
    @users = AdminUser.where(:category_id.nin=> Category.where(name: "SuperAdmin").pluck(:id)).order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    end

    @notifications = Notification.all.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  end

  def notify
      @tab  = Tab.find_by(id: params[:tab_id])
      @notify = @tab.notifications.where(admin_user_id: params[:user_id], type: params[:type]).first
      if @notify.present?  
        @notify.update(type: params[:type])
        flash[:notice] = "User Added Successfully."
        redirect_to admin_category_tab_notifications_path(params[:category_id], @tab)
      else
       @notification =  @tab.notifications.new(notification_params)
        if @notification.save
          flash[:notice] = "User Added Successfully."
          redirect_to  admin_category_tab_notifications_path(params[:category_id], @tab)
        end  
      end      
   end

   def destroy
     @notification = Notification.find_by(id: params[:id])
     @notification.destroy
     redirect_to request.referer, notice: "Deleted Successfully"
   end


  private
  def notification_params
    params[:admin_user_id]= params[:user_id]
    params.permit(:admin_user_id, :type)
  end
end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
	def user id
		AdminUser.find_by(id: id)
	end
end

app/views/admin/notifications/index.html.erb
     <head>
    <style>
body {font-family: Arial;}

/* Style the tab */
.tab {
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #ffffff;
    height: 56px;
}

/* Style the buttons inside the tab */
.tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
    font-size: 17px;
    height: 100%;
}

/* Change background color of buttons on hover */
.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}
</style>
</head>
<body>
<div class="tab">
  <input type="button" class="tablinks" onclick="opentabform(event, 'listing')" id="defaultOpen" value="listing" />
  <input type="button" class="tablinks" onclick="opentabform(event, 'added_user')" id="defaultOpen" value="added_user" />
</div>

   <%#=form_for :category, url: admin_categories_path, html: {:id=> "create-category"} do |f|%>
<%#@show_tabs.each do |tab|%>
<div id="listing" class="tabcontent">
   <section class="content-header">
      <!-- <h1>
        Category
      </h1> -->
      <!-- <h1> -->
        <form action="<%= admin_category_tab_notifications_path %>"  method="get" >
            <input type="text" name="search" placeholder="Search User"> 
          <button class="btn-primary">Search</button>
      </form>
      <!-- </h1> -->
      <ol class="breadcrumb">
        <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li> -->
      </ol>
    </section>
    <!-- Main content -->
    <section class="content" >
          
        
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Emp Id</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Action</th>
                    <!-- <th>Territory</th> -->
                </tr>
                </thead>
                <tbody>
                <% @users.each do |user|%>
                  <tr>
                    <td><%= user&.emp_id%></td>
                    <td><%= user&.first_name%></td>
                    <%= form_tag notify_admin_category_tab_notifications_path(category_id: params[:category_id], tab_id: params[:tab_id]), method: :post do %>
                    <td><%= select_tag :type, options_for_select([["select", ""],"Approved", "Approved and Notify", "Notify"]), required: true %></td>
                    <td><%#=link_to '<button class = "btn-primary"> Add</button>'.html_safe, "#"%>
                        <input type="hidden" name="user_id" value="<%=user.id%>">
                        <%= submit_tag 'Add'.html_safe, :class=>"btn btn-sm btn-primary", style: "width: 99px;" %>
                      <%end%>
                      
                    </td>
                  </tr>
                  <%end%>
                </tbody>
              </table>
    <div class="custom-pagination pull-right">
    <%= will_paginate @users %>
    </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
</div>
<div id="added_user" class="tabcontent">

  <section class="content-header">
      <!-- <h1>
        Category
      </h1> -->
      <!-- <h1> -->
        
      <!-- </h1> -->
      <ol class="breadcrumb">
        <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li> -->
      </ol>
    </section>
    <!-- Main content -->
    <section class="content" >
          
        
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Emp Id</th>
                    <th>Manager</th>
                    <th>Type</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <% @notifications.each do |notification|%>
                  <tr>
                    <td><%= user(notification&.admin_user_id)&.emp_id %></td>
                    <td><%= user(notification&.admin_user_id)&.first_name%></td>
                    <td><%= notification&.type%></td>
                    <td>
                      <div class="action-btn">
                      <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe, admin_category_tab_notification_path(id: notification.id),:class=>"btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                    </div>
                      <%#= link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe, admin_category_tab_notification_path(id: notification.id), :class=>"btn btn-sm btn-danger", mehtod: :delete ,:data => {:confirm => 'Are you sure?'}%>
                    </td>
                    </td>
                  </tr>
                  <%end%>
                </tbody>
              </table>
    <div class="custom-pagination pull-right">
    <%= will_paginate @users %>
    </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
   
</div>

<%#end%>


<%#=f.submit "Create Category", class: "btn-primary"%> 
<%#end%>
<script>
function opentabform(evt, tab_name) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tab_name).style.display = "block";
    evt.currentTarget.className += " active";
}
   document.getElementById("defaultOpen").click();
</script>


<script type="text/javascript">
  $(".create-col").attr("disabled",true);
</script>