config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :categories do
       resources :tabs do 
           collection do
             post :render_table
             post :render_table_table
           end
           resources :notifications do
             collection do
                post :notify
             end  
           end   
       end
    end#, only: [:new,:create, :edit, :update, :index]
    resources :accounts 
    resources :admin_users do
      collection{
        post :import
        post :export
        post :send_credential
        get :suspend_user
      }
    end
    get 'accounts/index'
    get 'sessions/login'
    post "sessions/create"
    delete "sessions/destroy"
    get "dashboard/home"
    get "sessions/forgot_password"
    post "password_resets/send_reset_password"
    get "/password_resets/reset_password"
    put "/password_resets/update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # post 'auth/login', to: 'users#login'
  # get 'test', to: 'users#test'
  get "/create_session", to: "admin/tabs#create_session"
  resources :exportdata do
      collection do
        get :exportxls
      end 
    end
  
  post 'phone_verifications/voice' => 'api/v1/phone_verifications#voice'

  api_version(:module => "api/V1", :header => {:name => "Accept", :value => "application/Wavedio; version=1"}) do
  	resources :sessions do
	  	collection do
	  		post :login
	  		post :verify_otp
        post :social_login
        post :call_verification
        post :logout
	  	end 
  	end
  	resources :static_contents do
  		collection do
  			post :static_contents
        get :faqs
        get :additional_topic
        post :query
  		end
  	end
    resources :devices do
      collection do
        post :search_device
        post :device_locations
        post :stolen_device_location_update
        post :device_location_search
        post :device_status
        post :save_battery_ts
      end
    end
    resources :packages do
      collection do
        get :packages_list
      end
    end
    resources :users do
      collection do
        post :apply_credit
        post :charge_history
        get :user_last_charge
        post :checksum
        post :billing_not_rated
        post :charging_status
        post :checksum_add_money
        post :add_money_transaction_status
        post :billing_status
      end
    end
    
    resources :help do 
       collection do
         get :get_b1_b2_list
         post :submit_b1_b2
         get :feedback_and_faq_list
         get :r1_r2_list
         post :submit_feedback_api
       end
    end

    resources :transactions do
      collection do
        post :package_payment
        post :send_paytm_otp
        post :validate_paytm_otp
        post :check_paytm_balance
        post :validate_paytm_access_token
        post :paytm_withdraw_api
      end
    end

    resources :payment_methods do 
       collection do 
         get :list
         post :add
         post :remove
       end
    end

  #   resources :phone_verifications do
  #     collection do
  #       post :voice
  #     end
  #   end

end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin_lte_2'
  before_action :authenticate_admin_user
  def home
     if params[:tab_id].present?
        @tab  = Tab.find_by(id: params[:tab_id])
        @show_tabs = @tab.columns.keys 
        @show = @tab.columns
        @tab_type = @tab.type
        p "#{@tab_type}"
        @table_name = @tab.columns.keys.first
        @model_name  = @tab.columns.keys.first.camelize.constantize
        
        @model_object = @model_name.new
        
        @table_field_keys = @tab.columns[@table_name].keys
     
     end
  end


end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
 
  
end

app/views/admin/dashboard/_tab_form.html.erb
<%=form_for [:admin,@model_object] do |f|%>
  <%@table_field_keys = @tab.columns[@table_name].keys%>
  <%@table_field_keys.each do |key|%>
    <% if @tab.columns[@table_name][key].include?("create")%>
      <%=f.label "#{key}"%><br>
      <%=f.text_field "#{key}", required: @tab.columns[@table_name][key].include?("compulsary").present? ? true : false %><br>
    <%end%>
  <%end%>

<%=f.submit "Create #{@table_name.capitalize}"%>  
<%end%>

app/views/admin/dashboard/_tab_table.html.erb
     <head>
    <style>
body {font-family: Arial;}

/* Style the tab */
.tab {
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #ffffff;
    height: 56px;
}

/* Style the buttons inside the tab */
.tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
    font-size: 17px;
    height: 100%;
}

/* Change background color of buttons on hover */
.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}
</style>
</head>
<body>
    <br>Tab Name:<%= @tab.name%>
<div class="tab">
<%@show_tabs.each do |tab|%>
  <input type="button" class="tablinks" onclick="opentabform(event, '<%=tab%>')" id="defaultOpen" value="<%=tab%>" />
<%end%>
</div>

   <%#=form_for :category, url: admin_categories_path, html: {:id=> "create-category"} do |f|%>
<%@show_tabs.each do |tab|%>
<div id="<%=tab%>" class="tabcontent">
   <table class="table table-bordered table-hover">
        <thead>
        <tr>
<!--         <th>Columns Name</th>
        <th>View</th>
        <th>Compulsary</th>
        <th>Deactive</th> -->
         <%unless @show[tab].keys.nil?%>
          <% @show["#{tab}"].keys.each do |col|%>
        <th><%= col%></th>
        <%end%>
        <%end%>
        </tr>
        </thead>
        <tbody>
          <%#binding.pry%>
          <%unless @show[tab].keys.nil?%>

      <% @show["#{tab}"].keys.each do |col|%>
        <tr>
      <!-- <td><%= col%></td>
      <td>
        <%#if @show["#{tab}"][col].include?("view")%>
        <input type="checkbox"  class="create-col" checked/>
        <%#else%>
        <input type="checkbox" class="create-col"/>
        <%#end%>

      </td> -->
      <!-- <td>
        <%#if @show["#{tab}"][col].include?("compulsary")%>
        <input type="checkbox"  class="create-col" checked>
        <%#else%>
        <input type="checkbox" class="create-col"/>
        <%#end%>
      </td>
      <td>
        <%#if @show["#{tab}"][col].include?("deactive")%>
        <input type="checkbox" class="create-col" checked>
        <%#else%>
        <input type="checkbox" class="create-col"/>
        <%#end%>

      </td> -->
    </tr>

    <%end%>
    <%end%>
  </tbody>
</table>
</div>
<%end%>


<%#=f.submit "Create Category", class: "btn-primary"%> 
<%#end%>
<script>
function opentabform(evt, tab_name) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tab_name).style.display = "block";
    evt.currentTarget.className += " active";
}
   document.getElementById("defaultOpen").click();
</script>


<script type="text/javascript">
  $(".create-col").attr("disabled",true);
</script>

app/views/admin/dashboard/get_tab_value.html.erb
<%= params[:tab_id]%><br>
<%= params[:table_name].camelize%>
<%= form_tag admin_dashboard_set_tab_value_path(id: params[:tab_id], table_name: params[:table_name]) do %>
<% column = Tab.find_by(id: params[:tab_id]).columns%><br>
<% column[:"#{params[:table_name].downcase}"].keys.each do |field| %>
	<% table_name_field = params[:table_name]%>
	<%= "#{field.camelize}"%><br><%#= text_field_tag :"#{field}" %><%= text_field_tag :"tab_value[:#{table_name_field}][:#{field}]" %><br>
<%end%>

<br>
<br>
<%= submit_tag 'Send'.html_safe, :class=>"btn btn-sm btn-info", style: "width: 99px;" %>
   <%end%>

app/views/admin/dashboard/home.html.erb
<%if super_admin_user?%>
    <div class="center" style="padding-right: 400px" style="padding-left: 400px">
      
     <div class="action-btn" align="center" style="padding-bottom: 10px">
            <a>
              <%= link_to 'Create Category'.html_safe, new_admin_category_path, :class=>"btn btn-block btn-info btn-lg"%>
            </a>
     </div>

     <div class="action-btn" align="center" style="padding-bottom: 10px">
            <a>
              <%= link_to 'HR USERS'.html_safe, admin_admin_users_path, :class=>"btn btn-block btn-info btn-lg"%>
            </a>
     </div>

     <div class="action-btn" align="center" style="padding-bottom: 10px">
            <a>
              <%= link_to 'View Categories'.html_safe, admin_categories_path , :class=>"btn btn-block btn-info btn-lg" %>
            </a>
     </div>
    </div>
<%else%>
    <%if Tab.find_by(id: params[:tab_id])&.type == "table" %>
    <%= Tab.find_by(id: params[:tab_id])&.type %>
    <%= render "tab_table"%>
    <%elsif Tab.find_by(id: params[:tab_id])&.type == "form" %>
    <%= Tab.find_by(id: params[:tab_id])&.type %>
    <%= render "tab_form"%>
    <%end%>
<%end%>