config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :categories do
       resources :tabs do 
           collection do
             post :render_table
             post :render_table_table
           end
           resources :notifications do
             collection do
                post :notify
             end  
           end   
       end
    end#, only: [:new,:create, :edit, :update, :index]
    resources :accounts 
    resources :admin_users do
      collection{
        post :import
        post :export
        post :send_credential
        get :suspend_user
      }
    end
    get 'accounts/index'
    get 'sessions/login'
    post "sessions/create"
    delete "sessions/destroy"
    get "dashboard/home"
    get "sessions/forgot_password"
    post "password_resets/send_reset_password"
    get "/password_resets/reset_password"
    put "/password_resets/update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # post 'auth/login', to: 'users#login'
  # get 'test', to: 'users#test'
  get "/create_session", to: "admin/tabs#create_session"
  resources :exportdata do
      collection do
        get :exportxls
      end 
    end
  
  post 'phone_verifications/voice' => 'api/v1/phone_verifications#voice'

  api_version(:module => "api/V1", :header => {:name => "Accept", :value => "application/Wavedio; version=1"}) do
  	resources :sessions do
	  	collection do
	  		post :login
	  		post :verify_otp
        post :social_login
        post :call_verification
        post :logout
	  	end 
  	end
  	resources :static_contents do
  		collection do
  			post :static_contents
        get :faqs
        get :additional_topic
        post :query
  		end
  	end
    resources :devices do
      collection do
        post :search_device
        post :device_locations
        post :stolen_device_location_update
        post :device_location_search
        post :device_status
        post :save_battery_ts
      end
    end
    resources :packages do
      collection do
        get :packages_list
      end
    end
    resources :users do
      collection do
        post :apply_credit
        post :charge_history
        get :user_last_charge
        post :checksum
        post :billing_not_rated
        post :charging_status
        post :checksum_add_money
        post :add_money_transaction_status
        post :billing_status
      end
    end
    
    resources :help do 
       collection do
         get :get_b1_b2_list
         post :submit_b1_b2
         get :feedback_and_faq_list
         get :r1_r2_list
         post :submit_feedback_api
       end
    end

    resources :transactions do
      collection do
        post :package_payment
        post :send_paytm_otp
        post :validate_paytm_otp
        post :check_paytm_balance
        post :validate_paytm_access_token
        post :paytm_withdraw_api
      end
    end

    resources :payment_methods do 
       collection do 
         get :list
         post :add
         post :remove
       end
    end

  #   resources :phone_verifications do
  #     collection do
  #       post :voice
  #     end
  #   end

end

end

app/models/tab.rb
class Tab
  include Mongoid::Document
  field :name, type: String
  field :type, type: String
  field :category_id, type: String
  field :is_active, type: Boolean, default: true
  field :columns, type: Hash, default: {}
  field :value, type: Hash, default: {:tab_values => {}}

  belongs_to :category
  has_many :tab_tables, dependent: :destroy
  has_many :notifications, dependent: :destroy
  validates :name, :presence => true, length: {minimum: 3, maximum: 30} ,format: { with: /[A-Za-z ]+/}
end

app/models/tab_table.rb
class TabTable
  include Mongoid::Document
  field :tab_id, type: String
  field :table_name, type: String
  field :table_columns, type: Hash, default: {}
  belongs_to :tab

end

app/controllers/admin/tabs_controller.rb
require 'will_paginate/array'

class Admin::TabsController < ApplicationController
  layout 'admin_lte_2'
  before_action :authenticate_admin_user
  def index
  	@category = Category.find_by(id: params[:category_id])
  	@tabs = @category.tabs.order("created_at desc").reverse.paginate(:page => params[:page], :per_page => 15)
  end

  def new
  	@category = Category.find_by(id: params[:category_id])
    @tab = @category.tabs.new	  
  end

  def create
    @category = Category.find_by(id: params[:category_id])
     binding.pry
     @tab = @category.tabs.new(name: params[:tab][:name], type: params[:tab][:type], columns: params[:tab][:columns].to_unsafe_hash)
     if @tab.save
          session[:table_name] = []
          # @tab.update(columns: params[:tab][:columns].to_unsafe_hash)
          flash[:notice] =  "Tab created successfully"
          redirect_to admin_category_tabs_path       
     end
  end

  def show
    @tab = Tab.find_by(id: params[:id])
    @show = @tab.columns
    @show_tabs = @tab.columns.keys 
   
  end

  def edit
   @tab = Tab.find_by(id: params[:id])
   @show = @tab.columns
   @show_tabs = @tab.columns.keys 
   if @tab.type == 'form'
    @account_columns = ["name", "contact_person", "contact_email", "contact_mobile", "potential_site", "emp_id"]
    @lead_columns = ["site_name", "location_address", "address", "lat", "long", "account_id", "site_person", "site_mobile", "estimated_value", "sales_emp_id", "attachment", "quotation_id", "emp_remarks", "escalation_one", "escalation_two", "status_one", "status_two", "site_manager_id", "manager_id", "est_close_date", "s1_close_date", "s2_close_date", "manager_remark"] 
    @quotation_columns = ["site_id", "device_quantity", "hub_quantity", "one_time_retail_fee", "manager_approval", "qt_approval_date"] 
    @ddd_columns = [ "quotation_id", "site_id", "site_name", "site_location", "quotation_date", "device_id", "device_type", "attachment", "d3_id", "d3_creation_date", "wh_pickup_date"] 
   elsif @tab.type == 'table'
    @account_columns = ["_id","created_at","name", "contact_person", "contact_email", "contact_mobile", "potential_site", "emp_id"]
    @lead_columns = ["_id","created_at","site_name", "location_address", "address", "lat", "long", "account_id", "site_person", "site_mobile", "estimated_value", "sales_emp_id", "attachment", "quotation_id", "emp_remarks", "escalation_one", "escalation_two", "status_one", "status_two", "site_manager_id", "manager_id", "est_close_date", "s1_close_date", "s2_close_date", "manager_remark"] 
    @quotation_columns = ["_id","created_at","site_id", "device_quantity", "hub_quantity", "one_time_retail_fee", "manager_approval", "qt_approval_date"] 
    @ddd_columns = [ "_id","created_at","quotation_id", "site_id", "site_name", "site_location", "quotation_date", "device_id", "device_type", "attachment", "d3_id", "d3_creation_date", "wh_pickup_date"]  
   end
   @site_mgmt_columns = ["lead_id", "d3_id", "site_manager", "site_installer_id", "site_installer_status_report", "attachment", "site_approval", "site_activation_date"]
   @warehouse_columns = ["device_id", "qr_code", "product_type", "warehouse_received_date", "iqc_report", "device_status"]


  end

  def update
     @tab = Tab.find_by(id: params[:id])
     if @tab.update(name: params[:tab][:name], columns: params[:tab][:columns].to_unsafe_hash)
      redirect_to admin_category_tabs_path, notice: "Tab Updated Successfully"
    end
  end 

  def destroy
    
  end

  def render_table #form_table
      @account_columns = ["name", "contact_person", "contact_email", "contact_mobile", "potential_site", "emp_id"]
      @lead_columns = ["site_name", "location_address", "address", "lat", "long", "account_id", "site_person", "site_mobile", "estimated_value", "sales_emp_id", "attachment", "quotation_id", "emp_remarks", "escalation_one", "escalation_two", "status_one", "status_two", "site_manager_id", "manager_id", "est_close_date", "s1_close_date", "s2_close_date", "manager_remark"] 
      @quotation_columns = ["site_id", "device_quantity", "hub_quantity", "one_time_retail_fee", "manager_approval", "qt_approval_date"] 
      @ddd_columns = [ "quotation_id", "site_id", "site_name", "site_location", "quotation_date", "device_id", "device_type", "attachment", "d3_id", "d3_creation_date", "wh_pickup_date"] 
      @warehouse_columns = ["device_id", "qr_code", "product_type", "warehouse_received_date", "iqc_report", "device_status"]
      @site_mgmt_columns = ["lead_id", "d3_id", "site_manager", "site_installer_id", "site_installer_status_report", "attachment", "site_approval", "site_activation_date"]
      @user_columns = ["first_name", "last_name", "email", "mobile", "last_login", "imei", "lat", "long", "address", "created_at", "mobile_phone_mobel", "credit"]
      @device_columns = ["device", "stolen", "mac_address", "identifier","site_display_name", "ido_old", "ido_new","site_id"]
      @tab_type = params[:type]
  end

  def render_table_table
      @account_columns = ["_id","created_at","name", "contact_person", "contact_email", "contact_mobile", "potential_site", "emp_id"]
      @lead_columns = ["_id","created_at","site_name", "location_address", "address", "lat", "long", "account_id", "site_person", "site_mobile", "estimated_value", "sales_emp_id", "attachment", "quotation_id", "emp_remarks", "escalation_one", "escalation_two", "status_one", "status_two", "site_manager_id", "manager_id", "est_close_date", "s1_close_date", "s2_close_date", "manager_remark"] 
      @quotation_columns = ["_id","created_at","site_id", "device_quantity", "hub_quantity", "one_time_retail_fee", "manager_approval", "qt_approval_date"] 
      @ddd_columns = [ "_id","created_at","quotation_id", "site_id", "site_name", "site_location", "quotation_date", "device_id", "device_type", "attachment", "d3_id", "d3_creation_date", "wh_pickup_date"]  
      @warehouse_columns = ["device_id", "qr_code", "product_type", "warehouse_received_date", "iqc_report", "device_status"]
      @site_mgmt_columns = ["lead_id", "d3_id", "site_manager", "site_installer_id", "site_installer_status_report", "attachment", "site_approval", "site_activation_date"]
      @user_columns = ["_id","first_name", "last_name", "email", "mobile", "last_login", "imei", "lat", "long", "address", "created_at", "mobile_phone_mobel", "credit"]
      @device_columns = ["device", "stolen", "mac_address", "identifier","site_display_name", "ido_old", "ido_new","site_id"]

      @tab_type = params[:type]
    # @column_names = params[:table].camelize.constantize.attribute_names - ["updated_at"]
    # @tab_type = params[:type]
  end

  # def checkbox_session
  #   session ||=[]
  # @session_hash ||= {}
  # @session_hash[params[:table]] ||= {}
  # @session_hash[params[:table]]["view"] ||= []
  # @session_hash[params[:table]]["view"] << params[:table_column]
  # @session <<  @session_hash
  # p session
  
  # end

  def create_session
    if session[:table_name].present?
       if params[:empty].present?
         session[:table_name].delete(params[:table_name].downcase)
        return if params[:empty] == "true"
       end
       return render json: {status: true} if session[:table_name].include?(params[:table_name])
       associations = params[:table_name].camelize.constantize.reflect_on_all_associations.map(&:name).map(&:to_s).map(&:singularize)
       count = 0
       session[:table_name].each do |table_name|
          count = (count + 1)  if associations.include?(table_name)   
       end
        if count > 0
        p "*********true***********"
         session[:table_name] << params[:table_name].downcase unless session[:table_name].include?(params[:table_name].downcase)
          return render json: {status: true} 
       elsif count == 0 
        p "*********false***********"
          return render json: {status: false}
       end

    else
      session[:table_name] ||= [] 
      params[:table_name] = params[:table_name].downcase.singularize
      session[:table_name] << params[:table_name]
      return render json: {status: true}
    end
    
  end
  

  private
  def tab_params
    # params[:tab][:columns] = params[:tab][:columns].to_unsafe_hash 
    params.require(:tab).permit(:name, :type)   
  end 
end

app/helpers/admin/tabs_helper.rb
module Admin::TabsHelper
  def check_create tab, column_name
  	return true if tab&.tab_tables&.first&.table_columns["create"]&.include?(column_name)
  end


  def check_deactive tab,column_name
    return true if tab&.tab_tables&.first&.table_columns["deactive"]&.include?(column_name)
  end

  def check_compulsary tab,column_name
  	return true if tab&.tab_tables&.first&.table_columns["compulsary"]&.include?(column_name)
  end

end

app/views/admin/tabs/_common.html.erb
<%begin%>
      	<%if @show[column_name][tab].include?(tab_type)%>	
      	<input type="checkbox" name="tab[columns][<%=column_name%>[<%=tab%>]][]" value="<%=tab_type%>" class="view-col" checked>
      	<%else%>
      	<input type="checkbox" name="tab[columns][<%=column_name%>[<%=tab%>]][]" value="<%=tab_type%>" class="view-col">
        <%end%>
        <%rescue Exception=>e%>
        <input type="checkbox" name="tab[columns][<%=column_name%>[<%=tab%>]][]" value="<%=tab_type%>" class="view-col">
      <%end%>

app/views/admin/tabs/_edit_form.html.erb
 <%=form_for(@tab, url: admin_category_tab_path, method: :patch , html: {:id=> "create-tabs"})do |f|%>
  <%=f.label :name, " Tab Name"%>
  <%=f.text_field :name%> <br>



     <head>
    <style>
body {font-family: Arial;}

/* Style the tab */
.tab {
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #ffffff;
    height: 56px;
}

/* Style the buttons inside the tab */
.tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
    font-size: 17px;
    height: 100%;
}

/* Change background color of buttons on hover */
.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}
</style>
</head>
<body>
<div class="tab">
  <input type="button" class="tablinks" onclick="opentabform(event, 'Account')"id="defaultOpen" value="Account" />
  <input type="button" class="tablinks" onclick="opentabform(event, 'Lead')"id="defaultOpen" value="Lead" />
  <input type="button" class="tablinks" onclick="opentabform(event, 'Quotation')"id="defaultOpen" value="Quotation" />
  <input type="button" class="tablinks" onclick="opentabform(event, 'deployment_document_datum')"id="defaultOpen" value="Deployment_document_datum"  />
<!--   <button class="tablinks" onclick="opentabform(event, 'Lead')">Lead</button>
  <button class="tablinks" onclick="opentabform(event, 'Quotation')">Quotation</button>
  <button class="tablinks" onclick="opentabform(event, 'User')">User</button>
 --></div>

   <%#=form_for :category, url: admin_categories_path, html: {:id=> "create-category"} do |f|%>
<div id="Account" class="tabcontent">
   <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>Create</th>
        <th>Compulsary</th>
        <th>Deactive</th>
        </tr>
        </thead>
        <tbody>
      <% @account_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
      
      <td>
      	<%=render "common", column_name: "account", tab: tab, tab_type: "create"%>
      </td>
      <td>
      	<%=render "common", column_name: "account", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%=render "common", column_name: "account", tab: tab, tab_type: "deactive"%>
      </td>
      
    </tr>

    <%end%>
  </tbody>
</table>
</div>

<div id="Lead" class="tabcontent">
  <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>Create</th>
        <th>Compulsary</th>
        <th>Deactive</th>
        </tr>
        </thead>
        <tbody>
      <% @lead_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
     <td>
      	<%=render "common", column_name: "lead", tab: tab, tab_type: "create"%>
      </td>
      <td>
      	<%=render "common", column_name: "lead", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%=render "common", column_name: "lead", tab: tab, tab_type: "deactive"%>
      </td>
      
    </tr>

    <%end%>
  </tbody> 
</table>
</div>


<div id="Quotation" class="tabcontent">
 <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>Create</th>
        <th>Compulsary</th>
        <th>Deactive</th>
        </tr>
        </thead>
        <tbody>
      <% @quotation_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
      <td>
      	<%=render "common", column_name: "quotation", tab: tab, tab_type: "create"%>
      </td>
      <td>
      	<%=render "common", column_name: "quotation", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%=render "common", column_name: "quotation", tab: tab, tab_type: "deactive"%>
      </td>
      
    </tr>

    <%end%>
  </tbody>
</table>
</div>

<div id="deployment_document_datum" class="tabcontent">
  <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>Create</th>
        <th>Compulsary</th>
        <th>Deactive</th>
        </tr>
        </thead>
        <tbody>
      <% @ddd_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
     <td>
      	<%=render "common", column_name: "deployment_document_datum", tab: tab, tab_type: "create"%>
      </td>
      <td>
      	<%=render "common", column_name: "deployment_document_datum", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%=render "common", column_name: "deployment_document_datum", tab: tab, tab_type: "deactive"%>
      </td>
      
    </tr>

    <%end%>
  </tbody>
</table>
</div>
<%#=f.submit "Create Category", class: "btn-primary"%> 
<%=f.submit "Update Tab", :class=>"btn-primary"%>
<%#end%>
  <%end%>
<script>
function opentabform(evt, tab_name) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tab_name).style.display = "block";
    evt.currentTarget.className += " active";
}
   document.getElementById("defaultOpen").click();
</script>

app/views/admin/tabs/_edit_table.html.erb
 <%=form_for(@tab, url: admin_category_tab_path, method: :patch , html: {:id=> "create-tabs"})do |f|%>
  <%=f.label :name, " Tab Name"%>
  <%=f.text_field :name%> <br>


     <head>
    <style>
body {font-family: Arial;}

/* Style the tab */
.tab {
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #ffffff;
    height: 56px;
}

/* Style the buttons inside the tab */
.tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
    font-size: 17px;
    height: 100%;
}

/* Change background color of buttons on hover */
.tab button:hover {
    background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
    background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}
</style>
</head>
<body>
<div class="tab">
  <input type="button" class="tablinks" onclick="opentabform(event, 'Account')"id="defaultOpen" value="Account" />
  <input type="button" class="tablinks" onclick="opentabform(event, 'Lead')"id="defaultOpen" value="Lead" />
  <input type="button" class="tablinks" onclick="opentabform(event, 'Quotation')"id="defaultOpen" value="Quotation" />
  <input type="button" class="tablinks" onclick="opentabform(event, 'deployment_document_datum')"id="defaultOpen" value="Deployment_document_datum"  />
<!--   <button class="tablinks" onclick="opentabform(event, 'Lead')">Lead</button>
  <button class="tablinks" onclick="opentabform(event, 'Quotation')">Quotation</button>
  <button class="tablinks" onclick="opentabform(event, 'User')">User</button>
 --></div>

   <%#=form_for :category, url: admin_categories_path, html: {:id=> "create-category"} do |f|%>
<div id="Account" class="tabcontent">
   <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>View</th>
        <!-- <th>Compulsary</th>
        <th>Deactive</th> -->
        </tr>
        </thead>
        <tbody>
      <% @account_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
      
      <td>
      	<%=render "common", column_name: "account", tab: tab, tab_type: "view"%>
      </td>
      <!-- <td>
      	<%#=render "common", column_name: "account", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%#=render "common", column_name: "account", tab: tab, tab_type: "deactive"%>
      </td> -->
      
    </tr>

    <%end%>
  </tbody>
</table>
</div>

<div id="Lead" class="tabcontent">
  <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>View</th>
        <!-- <th>Compulsary</th>
        <th>Deactive</th> -->
        </tr>
        </thead>
        <tbody>
      <% @lead_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
     <td>
      	<%=render "common", column_name: "site", tab: tab, tab_type: "view"%>
      </td>
      <!-- <td>
      	<%#=render "common", column_name: "lead", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%#=render "common", column_name: "lead", tab: tab, tab_type: "deactive"%>
      </td> -->
      
    </tr>

    <%end%>
  </tbody> 
</table>
</div>


<div id="Quotation" class="tabcontent">
 <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>View</th>
        <!-- <th>Compulsary</th>
        <th>Deactive</th> -->
        </tr>
        </thead>
        <tbody>
      <% @quotation_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
      <td>
      	<%=render "common", column_name: "quotation", tab: tab, tab_type: "view"%>
      </td>
     <!--  <td>
      	<%#=render "common", column_name: "quotation", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%#=render "common", column_name: "quotation", tab: tab, tab_type: "deactive"%>
      </td> -->
      
    </tr>

    <%end%>
  </tbody>
</table>
</div>

<div id="deployment_document_datum" class="tabcontent">
  <table class="table table-bordered table-hover">
        <thead>
        <tr>
        <th>Columns Name</th>
        <th>View</th>
        <!-- <th>Compulsary</th>
        <th>Deactive</th> -->
        </tr>
        </thead>
        <tbody>
      <% @ddd_columns.each do |tab|%>
        <tr>
      <td><%= tab%></td>
     <td>
      	<%=render "common", column_name: "deployment_document_datum", tab: tab, tab_type: "view"%>
      </td>
     <!--  <td>
      	<%#=render "common", column_name: "deployment_document_datum", tab: tab, tab_type: "compulsary"%>
      </td>
      <td>
      	<%#=render "common", column_name: "deployment_document_datum", tab: tab, tab_type: "deactive"%>
      </td> -->
      
    </tr>

    <%end%>
  </tbody>
</table>
</div>
<%#=f.submit "Create Category", class: "btn-primary"%> 
<%=f.submit "Update Tab", :class=>"btn-primary"%>
<%#end%>
  <%end%>
<script>
function opentabform(evt, tab_name) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tab_name).style.display = "block";
    evt.currentTarget.className += " active";
}
   document.getElementById("defaultOpen").click();
</script>

app/views/admin/tabs/_form_table.html.erb
 
 <table class="table table-bordered table-hover">
				<thead>
				<tr>
				<th>Columns Name</th>
				<th>Create</th>
			    <th>Compulsary</th>
					<!-- <th>Territory</th> -->
				</tr>
				</thead>
				<tbody>
			<% @column_names.each do |tab|%>
	    	<tr>
			<td><%= tab%></td>
			<td><input type="checkbox" name="tab[column_names[create]][]" value="<%=tab%>" class="create-col"></td>
			<td><input type="checkbox" name="tab[column_names[compulsary]][]" value="<%=tab%>" class="com-col"></td>
		</tr>

		<%end%>
  </tbody>
</table>

app/views/admin/tabs/edit.html.erb
<% if @tab.type == 'form'%>
  <%=render "edit_form"%>
<% elsif @tab.type == 'table'%>
  <%=render "edit_table"%>
<% end%>

app/views/admin/tabs/index.html.erb
 <section class="content-header">
      <!-- <h1>
        Category
      </h1> -->
      <!-- <h1> -->
        <!-- <form action="#"  method="get" >
            <input type="text" name="search" placeholder="Search Tab"> 
          <button class="btn-primary">Search</button>
      </form> -->
      <!-- </h1> -->
      <ol class="breadcrumb">
        <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li> -->
      </ol>
    </section>
    <!-- Main content -->
    <section class="content" >
          <div class="action-btn" align="right" style="padding-bottom: 4px">
          <a><%= link_to '<i class="fa fa-edit" aria-hidden="true"></i> Create Tab'.html_safe, new_admin_category_tab_path(@category), :class=>"btn btn-sm btn-success"%>
          </a>
        </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> <%=@category&.name%></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Tab Name</th>
                    <th>Action</th>
                    <!-- <th>Territory</th> -->
                </tr>
                </thead>
                <tbody>
                <% @tabs.each do |tab|%>
                  <tr>
                    <td><%= tab&.name%></td>
                    <td><%=link_to "view tab", admin_category_tab_path(params[:category_id], tab)%>
                       <%=link_to "edit tab", edit_admin_category_tab_path(params[:category_id], tab)%> 
                    </td>
                  </tr>
                  <%end%>
                </tbody>
              </table>
    <div class="custom-pagination pull-right">
    <%= will_paginate @tabs %>
    </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->

app/views/admin/tabs/render_table.js.erb
<%if @tab_type=="form"%>
$("#table-columns").html("<%= escape_javascript(render("sample_table")) %>");
<%end%>

app/views/admin/tabs/render_table_table.js.erb
$("#table-columns").html("<%= escape_javascript(render("table_table")) %>");

app/views/admin/tabs/show.html.erb
<%if @tab.type == "form"%>
  <%=render "show_form"%>
<%elsif @tab.type == "table"%>
  <%=render "show_table"%>
<%end%>