config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :categories do
       resources :tabs do 
           collection do
             post :render_table
             post :render_table_table
           end
           resources :notifications do
             collection do
                post :notify
             end  
           end   
       end
    end#, only: [:new,:create, :edit, :update, :index]
    resources :accounts 
    resources :admin_users do
      collection{
        post :import
        post :export
        post :send_credential
        get :suspend_user
      }
    end
    get 'accounts/index'
    get 'sessions/login'
    post "sessions/create"
    delete "sessions/destroy"
    get "dashboard/home"
    get "sessions/forgot_password"
    post "password_resets/send_reset_password"
    get "/password_resets/reset_password"
    put "/password_resets/update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # post 'auth/login', to: 'users#login'
  # get 'test', to: 'users#test'
  get "/create_session", to: "admin/tabs#create_session"
  resources :exportdata do
      collection do
        get :exportxls
      end 
    end
  
  post 'phone_verifications/voice' => 'api/v1/phone_verifications#voice'

  api_version(:module => "api/V1", :header => {:name => "Accept", :value => "application/Wavedio; version=1"}) do
  	resources :sessions do
	  	collection do
	  		post :login
	  		post :verify_otp
        post :social_login
        post :call_verification
        post :logout
	  	end 
  	end
  	resources :static_contents do
  		collection do
  			post :static_contents
        get :faqs
        get :additional_topic
        post :query
  		end
  	end
    resources :devices do
      collection do
        post :search_device
        post :device_locations
        post :stolen_device_location_update
        post :device_location_search
        post :device_status
        post :save_battery_ts
      end
    end
    resources :packages do
      collection do
        get :packages_list
      end
    end
    resources :users do
      collection do
        post :apply_credit
        post :charge_history
        get :user_last_charge
        post :checksum
        post :billing_not_rated
        post :charging_status
        post :checksum_add_money
        post :add_money_transaction_status
        post :billing_status
      end
    end
    
    resources :help do 
       collection do
         get :get_b1_b2_list
         post :submit_b1_b2
         get :feedback_and_faq_list
         get :r1_r2_list
         post :submit_feedback_api
       end
    end

    resources :transactions do
      collection do
        post :package_payment
        post :send_paytm_otp
        post :validate_paytm_otp
        post :check_paytm_balance
        post :validate_paytm_access_token
        post :paytm_withdraw_api
      end
    end

    resources :payment_methods do 
       collection do 
         get :list
         post :add
         post :remove
       end
    end

  #   resources :phone_verifications do
  #     collection do
  #       post :voice
  #     end
  #   end

end

end

app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  include RememberMe::Model
  include ActiveModel::SecurePassword
  field :email, type: String
  field :password_digest, type: String
  field :remember_created_at,type: Time
  field :type, type: String
  field :reset_digest, type: String
  field :reset_token, type: String
  field :reset_created_at, type: Time
  field :category_id, type: String
  field :department, :type=> String 
  field :designation, :type=> String 
  field :territory, :type=> String
  field :emp_id, type: String
  field :manager_id, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :phone, type: String
  field :is_active?, type: Boolean, default: false
  has_secure_password validations: false
  belongs_to :category, optional: true
  validates :password, presence: false, :on => :create
  validates :password_confirmation, presence: false, :on => :create
  
  has_many :notifications

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      AdminUser.create! row.to_hash      
    end    
  end

  def self.export(options = {})
    headers = ['first_name','last_name','emp_id','email','phone','department','designation','territory']  
    dummy = ['Lalit','Saini','02091995','saini.lalitkmr@gmail.com','9876543210','ROR','dev','LA']  
    CSV.generate(options) do |csv|
      csv << headers
      csv << dummy
    end
  end

end

app/controllers/admin/admin_users_controller.rb
require 'will_paginate/array'
class Admin::AdminUsersController < ApplicationController
  layout 'admin_lte_2'
  before_action :authenticate_admin_user
  def index
    # @admin_user = AdminUser.where(id: session[:user_id]["$oid"]).first
    # category  = Category.find_by(name: "SuperAdmin")
    if params[:search].present?
    @search = AdminUser.any_of({first_name: Regexp.new(".*#{params[:search]}.*","i")},{last_name: Regexp.new(".*#{params[:search]}.*","i")},{emp_id: Regexp.new(".*#{params[:search]}.*","i")},{email: Regexp.new(".*#{params[:search]}.*","i")},{phone: Regexp.new(".*#{params[:search]}.*","i")},{department: Regexp.new(".*#{params[:search]}.*","i")},{designation: Regexp.new(".*#{params[:search]}.*","i")},{territory: Regexp.new(".*#{params[:search]}.*","i")})
    @admin_users = @search.where(:category_id.nin=> Category.where(name: "SuperAdmin").pluck(:id)).order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    # AdminUser.where(:category_id.nin=> Category.where(name: "SuperAdmin").pluck(:id))
    else
    @admin_users = AdminUser.where(:category_id.nin=> Category.where(name: "SuperAdmin").pluck(:id)).order("created_at desc").paginate(:page => params[:page], :per_page => 10)
    end
  end

  def send_credential
    # session[:return_to] ||= request.referer
    temp_password = SecureRandom.hex(7)
    AdminUser.find_by(id: params[:admin_user_id]).update(category_id: params[:categories], is_active?: true, password: temp_password, password_confirmation: temp_password)
    user_id = params[:admin_user_id]
    UserMailer.send_login_credential(user_id, temp_password).deliver_now!
    # redirect_to admin_admin_users_path, notice: "Send Successfully"
    # session[:return_to] = nil
    redirect_to request.referer, notice: "Send Successfully"
  end

  def suspend_user
    # session[:return_to] ||= request.referer
    AdminUser.find_by(id: params[:id]).update(is_active?: false)
    # redirect_to admin_admin_users_path, alert: "Suspended"
    # session[:return_to] = nil
    redirect_to request.referer, alert: "Account Suspended Successfully."
  end

  def import
    # session[:return_to] ||= request.referer
    AdminUser.import(params[:file])
    # redirect_to admin_admin_users_path, notice: "Users imported"    
    # session[:return_to] = nil
    redirect_to request.referer, notice: "HRMS User List imported."
  end

  def export
    @user = AdminUser.all
    respond_to do |format|
      format.html
      format.csv{ send_data @user.export,filename: "users-dummy-csv.csv"}
    end
  end
end

app/helpers/admin/admin_users_helper.rb
module Admin::AdminUsersHelper
  def get_categories
  	@categories = Category.where(:id.nin=> Category.where(name: "SuperAdmin").pluck(:id))
  end

  def send_login_credential user_id
  	
  end
end

app/views/admin/admin_users/index.html.erb
 <section class="content-header">
      <!-- <h1>
        Admin Users
      </h1> -->
      <!-- <h1> -->
        <form action="<%= admin_admin_users_path %>"  method="get" >
            <input type="text" name="search users" placeholder="Search"> 
          <button class="btn-btn-primary">Search</button>
      </form>
      <!-- </h1> -->
      <ol class="breadcrumb">
        <!-- <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li> -->
      </ol>
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
        <div class="action-btn" align="right" style="padding-bottom: 3px">
        <a>
          <%= link_to '<i class="fa fa-download" aria-hidden="true"></i> Export Sample'.html_safe, export_admin_admin_users_path(format: "csv") , method: :post, :class=>"btn btn-sm btn-info"%>
        </a>
      </div>
          <div class="box">
            <div class="box-header" style="display: block;">
                <%= form_tag import_admin_admin_users_path, multipart: true do %>
                <%= file_field_tag :file, required: true %>
              
                <%= submit_tag "Import", class: "btn-btn-primary" %>
                <%end%>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>First Name</th>
                    <th>Emp ID</th>
                    <th>User Email</th>
                    <th>Category</th>
                    <th>Send Login Credential</th>
                    <th>Action</th>
                    <!-- <th>Territory</th> -->
                </tr>
                </thead>
                <tbody>
                <% @admin_users.each do |admin_user|%>
                  <tr>
                    <td><%= admin_user&.first_name%></td>
                    <td><%= admin_user.try(:emp_id)%></td>
                    <!-- <td><span class="tag tag-success">Approved</span></td> -->
                    <td><%= admin_user.try(:email)%></td>
                    <td>
                      <%= form_tag send_credential_admin_admin_users_path(admin_user_id: admin_user.id), method: :post do %>
                      <%=select_tag "categories", options_from_collection_for_select(get_categories, "id", "name") %>
                  </td>
                  <td>  
                    <div class="action-btn">
                      <a>
                        <%= submit_tag 'Send'.html_safe, :class=>"btn btn-sm btn-info", style: "width: 99px;" %>
                      <%end%>
                          </a>
                    </div>
                    </td>
                   <td>
                    <div class="action-btn">
                     <% if admin_user&.is_active? == true %>
                 <a><%= link_to '<i class="fa fa-ban" aria-hidden="true"></i> Suspend'.html_safe, suspend_user_admin_admin_users_path(id: admin_user.id), :class=>"btn btn-sm btn-danger"  , style: "width: 99px;",:data => {:confirm => 'Are you sure you want to Suspend the User?'}%></a>
                 <% elsif admin_user&.is_active? == false %>
                 <a>
                  <span class="bg-green">
                    Inactive
                  </span>
                  <%#= link_to '<i class="fa fa-certificate" aria-hidden="true"></i> Inactive'.html_safe, "#", :class=>"btn btn-sm btn-success", style: "width: 99px;"%></a>
                 <% end %>
                 </div>
                   </td>
                  </tr>
                  <%end%>
                </tbody>
              </table>
    <div class="custom-pagination pull-right">
    <%= will_paginate @admin_users %>
    </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->